name: Generate Webpage for PR

on:
  pull_request:
    branches: [ master ]

jobs:
  webpage-gen-pr:
    runs-on: ubuntu-latest
    steps:

      - id: addKey
        name: Add key for staging push
        uses: webfactory/ssh-agent@ef0ce0cab8e3ad0aa0f3e1fb209b0811b68c0c51
        with:
          ssh-private-key: ${{ secrets.STAGING_KEY }}

      - uses: mshick/add-pr-comment@v1
        if: ${{ failure()  && steps.addKey.conclusion == 'failure' }}
        with:
          message: "Staging key could not be imported, cannot push to oscovida/staging to create test website instance. If this PR is external it may not have access to the required secrets."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false

      - name: Early exit for missing staging keys
        if: ${{ failure() && steps.addKey.conclusion == 'failure' }}
        uses: andymckay/cancel-action@0.2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout oscovida/staging
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.STAGING_KEY }}
          repository: oscovida/staging
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Checkout oscovida pr branch
        uses: actions/checkout@v2
        with:
          path: oscovida

      - name: Set up oscovida and webgen
        run: |
          pip install ./oscovida

      - name: Run pre-generate hook
        run: |
          ./oscovida/tools/oscovida.github.io/pre-generate.sh

      - name: Generate new reports
        run: |
          cp -r ./base ${{ github.event.number }}
          export WWWROOT=$(readlink -f ${{ github.event.number }})
          echo $WWWROOT
          cd ./oscovida/tools/
          ln -s $WWWROOT ./wwwroot
          ls ./wwwroot
          python3 -m report_generators.cli --debug --regions=all --workers=max --log-level=INFO --log-file=./wwwroot/report-gen.log

      - name: Run post-generate hook
        run: |
          ./oscovida/tools/oscovida.github.io/post-generate.sh

      - name: Update HTML pages
        run: |
          cd ./oscovida/tools/pelican
          make publish

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.number }} --all
          git commit -m "Generated preview for PR ${{ github.event.number }} on $(date)" -a
          git push

      - uses: mshick/add-pr-comment@v1
        with:
          message: "View web reports generated with this branch at [staging/${{ github.event.number }}/](https://oscovida.github.io/staging/${{ github.event.number }}/index.html)"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
