name: Run unit-tests for PR

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo python3 -m pip install --upgrade pip
          pip install -U pytest
          pip install pytest-tornasync setuptools
          make dev-install

      - name: Test with pytest
        run: |
          make test
          make test-pelican
          make test-nbval
      - uses: codecov/codecov-action@v1
